# Generated by Django 4.2.30 on 2026-05-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_email_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('category', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('data', 'Data / IA'), ('devops', 'DevOps / Cloud'), ('mobile', 'Mobile'), ('design', 'Design / UX'), ('other', 'Autre')], default='other', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Classe Bootstrap Icon (bi-...)', max_length=40)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='stageoffer',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text="URL de l'offre sur LinkedIn"),
        ),
        migrations.AddField(
            model_name='stageoffer',
            name='source',
            field=models.CharField(choices=[('local', 'Local'), ('linkedin', 'LinkedIn')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='stageoffer',
            name='required_tags',
            field=models.ManyToManyField(blank=True, related_name='offers', to='core.skilltag', verbose_name='Compétences requises (tags)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='skill_tags',
            field=models.ManyToManyField(blank=True, related_name='students', to='core.skilltag', verbose_name='Compétences (tags)'),
        ),
    ]
