# Generated by Django 4.2.30 on 2026-05-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_skilltag_stageoffer_linkedin_url_stageoffer_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_match_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
